#pragma once

#define DSGM_LARGE_BACKGROUND (void *)4

typedef enum {
	DSGM_LARGE_BACKGROUND_512,
	DSGM_LARGE_BACKGROUND_1024,
	DSGM_LARGE_BACKGROUND_2048,
	DSGM_LARGE_BACKGROUND_4096,
	DSGM_LARGE_BACKGROUND_8192,
} DSGM_LARGE_BACKGROUND_SIZES;

inline int DSGM_LargeBackgroundSizeToPixels(DSGM_LARGE_BACKGROUND_SIZES size);
